services:
  bot:
    image: ghcr.io/beerbunny/task-manager-bot:latest
    container_name: task_manager_bot
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  migrate:
    image: ghcr.io/beerbunny/task-manager-bot:latest
    container_name: task_manager_migrate
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: postgres:16
    container_name: task_manager_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: